Husky, eslint, prettier, lint-staged
skredmi/order-list pull request #3
Opened 2022-09-09 18:43 UTC by skredmi

2022-09-11 15:49 UTC, Muslik requested changes
У меня husky не запустился. Попробуйте склонить свой проект и попробовать сами.

2022-09-14 10:36 UTC, skredmi commented
Внес исправления. У меня запустился husky

2022-09-14 13:12 UTC, Muslik requested changes
https://asciinema.org/a/3UhZ0d7kp179vByPrcLJg1gho

2022-09-14 14:41 UTC, skredmi commented
Можно подсказку?! У меня работает, а у вас нет - из-за того, что у меня husky, lint-staged, prettier были установлены в dependencies?

2022-09-14 14:48 UTC, Muslik commented
> Можно подсказку?! У меня работает, а у вас нет - из-за того, что у меня husky, lint-staged, prettier были установлены в dependencies?

Ну по хорошему конечно да, их бы в devDeps установить. Но не работает не по этому. Вы попробуйте склонить репозиторий заново, у вас не заработает.
<img width="399" alt="Screenshot 2022-09-14 at 17 47 59" src="https://user-images.githubusercontent.com/15676404/190187749-67be4030-79d8-47e6-900b-e077222f4b38.png">
Выполните вот это.

2022-09-14 14:54 UTC, Muslik commented
> Можно подсказку?! У меня работает, а у вас нет - из-за того, что у меня husky, lint-staged, prettier были установлены в dependencies?

> Можно подсказку?! У меня работает, а у вас нет - из-за того, что у меня husky, lint-staged, prettier были установлены в dependencies?

Ну по хорошему конечно да, их бы в devDeps установить. Но не работает не по этому. Вы попробуйте склонить репозиторий заново, у вас не заработает.
<img width="399" alt="Screenshot 2022-09-14 at 17 47 59" src="https://user-images.githubusercontent.com/15676404/190187749-67be4030-79d8-47e6-900b-e077222f4b38.png">
Нужно было выполнить это и один раз запушить. Потом script prepare можно удалить. Сейчас у вас все работает :)

2022-09-14 14:54 UTC, Muslik approved these changes

2022-09-14 15:06 UTC, merged