Table
skredmi/order-list pull request #6
Opened 2022-10-30 18:54 UTC by skredmi

## 3. Собрать таблицу на mocks
  - [+] Минимум должны быть общие компоненты: Table, TableHeader, TableFooter, TableBody, TableRow, TableCell, TableHeaderCell, Checkbox
  - [+] В таблице есть 100 записей ([Можно сгенерировать](https://json-generator.com/)). Данные лежат в отдельном файле в константе.
  - [+] Body у таблицы корректно скроллится. Если у таблицы только один ряд, то футер никуда не уезжает а также корректно вытягивается на всю страницу

Добрый день! Посмотрите, пожалуйста.

2022-11-08 16:47 UTC, Muslik commented
<img width="165" alt="Screenshot 2022-11-08 at 19 46 30" src="https://user-images.githubusercontent.com/15676404/200625268-c9f8912e-3fff-4da6-b2ab-bdcac0dd21c2.png">
Все из папки components вынести на уровень выше. Очень странно что в папке с компонентами лежат еще папки components )

2022-11-08 16:51 UTC, Muslik requested changes

2022-11-08 16:51 UTC, Muslik commented on src/components/modules/ordersPage/components/TableFooter/TableFooter.jsx
> +export const TableFooter = () => {
Внимательно читайте ДЗ. Как я смогу переиспользовать ваш Footer? А никак

2022-11-08 16:51 UTC, Muslik commented on src/components/modules/ordersPage/components/TableHeader/TableHeader.jsx
> +export const TableHeader = () => (
Компонент непереиспользуем

2022-11-08 16:51 UTC, Muslik commented on src/components/modules/ordersPage/components/TableHeaderCell/TableHeaderCell.jsx
> +    {title} {Icon && <Icon nameIcon={nameIcon} className={styles.cellIcon} />}
Тут будет только одна иконка. Иконка со стрелочкой. Title можно вставлять children-ом

2022-11-08 16:51 UTC, Muslik commented on src/components/modules/ordersPage/components/TableHeaderCell/TableHeaderCell.jsx
> +    {title} {Icon && <Icon nameIcon={nameIcon} className={styles.cellIcon} />}
TableHeaderCell может иметь статус активный. Хотелось бы видеть пропс isActive

2022-11-08 16:51 UTC, Muslik commented on src/components/modules/ordersPage/components/TableRow/TableRow.jsx
> +const STATUS_MAP = {
Превратить это в компонент

2022-11-08 16:51 UTC, Muslik commented on src/components/modules/ordersPage/components/TableRow/TableRow.jsx
> +export const TableRow = ({
Компонент непереиспользуем

2022-11-08 16:51 UTC, Muslik commented on src/components/modules/ordersPage/components/TableBody/TableBody.jsx
> +  const [showOrders, setShowOrders] = useState([]);
Компонент непереиспользуем

2022-11-08 16:51 UTC, Muslik commented on src/components/modules/ordersPage/components/Table/Table.jsx
> +    <TableHeader />
Same

2022-11-08 16:51 UTC, Muslik commented on src/components/modules/ordersPage/components/Table/Table.module.css
> +  font-weight: 400;
Зачем этот тут. Это ж дефолтный шрифт

2022-11-08 19:33 UTC, skredmi commented
Сделал переиспользуемые компоненты, поправил структуру папок.

2022-11-08 21:08 UTC, skredmi commented
исправил замечания

2022-11-08 21:58 UTC, skredmi commented
Поправил отступы, появление "крестика" при наличии value у input

2022-11-12 14:42 UTC, Muslik approved these changes

2022-11-12 14:42 UTC, Muslik commented on src/components/modules/OrderTableBody/OrderTableBody.jsx
>    const [showOrders, setShowOrders] = useState([]);
Это тут не нужно. Пагинация будет дальше. Нижний useEffect тоже убрать

2022-11-12 14:42 UTC, Muslik commented on src/components/modules/OrderTableRow/OrderTableRow.jsx
> +      {status === "Отменен" ? "-" : count}
Это не нужно

2022-11-12 14:42 UTC, Muslik commented on src/components/modules/OrderTableRow/OrderTableRow.jsx
> +      {status === "Отменен" ? "-" : `${sum.toLocaleString("ru-RU")} ₽ `}
И это тоже.

2022-11-12 14:42 UTC, Muslik commented on src/components/modules/OrderTableRow/OrderTableRow.jsx
> +      {status === "Отменен" ? "-" : count}
Не нужно в смысле условие. Показывайте то что пришло вам в данных.

2022-11-12 14:42 UTC, Muslik commented on src/components/modules/TableStatusCell/TableStatusCell.jsx
> +    <div className={blockStatusClass}>
Ну тут явно TableCell должно быть

2022-11-12 15:39 UTC, merged